#
# This computer program is the confidential information and proprietary trade
# secret of Anuta Networks, Inc. Possessions and use of this program must
# conform strictly to the license agreement between the user and
# Anuta Networks, Inc., and receipt or possession does not convey any rights
# to divulge, reproduce, or allow others to use this program without specific
# written authorization of Anuta Networks, Inc.
#
# Copyright (c) 2015-2016 Anuta Networks, Inc. All Rights Reserved.
#

#
#DO NOT EDIT THIS FILE ITS AUTOGENERATED ONE
#ALL THE CUSTOMIZATIONS REGARDING DATAPROCESSING SHOULD BE WRITTEN INTO service_customization.py FILE
#
"""
Tree Structure of Handled XPATH:

services
        |
        day1services
                    |
                    day1service
                               |
                               cpe-finalize
                                     
Schema Representation:

/services/day1services/day1service/cpe-finalize
"""

from servicemodel import util
from servicemodel import yang
from servicemodel import devicemgr

from tclday0config.tclday0config_lib import getLocalObject
from tclday0config.tclday0config_lib import getDeviceObject
from tclday0config.tclday0config_lib import getCurrentObjectConfig
from tclday0config.tclday0config_lib import ServiceModelContext
from tclday0config.tclday0config_lib import getParentObject
from tclday0config.tclday0config_lib import log

from servicemodel.controller import devices
import service_customization


class CpeFinalize(yang.AbstractYangServiceHandler):
    _instance = None

    def __init__(self):
        self.delete_pre_processor = service_customization.DeletePreProcessor()
        self.create_pre_processor = service_customization.CreatePreProcessor()
        self.opaque_args = {}

    def create(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.create_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'cpe_finalize')

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['tacacs_credential_set'] = config.get_field_value('tacacs_credential_set')
        inputdict['device_mgmt_ip'] = config.get_field_value('device_mgmt_ip')
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address)

        # START OF FETCHING THE PARENT KEY LEAF PARAMETERS
        #inputkeydict['day1services_day1service_device_ip'] = sdata.getRcPath().split('/')[-2].split('=')[1]
        # END OF FETCHING THE PARENT KEY LEAF PARAMETERS

        #Use the custom methods to process the data
        service_customization.ServiceDataCustomization.process_service_create_data(smodelctx, sdata, dev, id=id, device=dev, parentobj=parentobj, inputdict=inputdict, inputkeydict=inputkeydict, config=config, hopaque=opaque_args)

        #Start of Device binding with python bindings
       
        #End of Device binding
        #devbindobjs['dummy_route_object'] = dummy_route_object
        #Use the custom method to process/create payload
        service_customization.ServiceDataCustomization.process_service_device_bindings(smodelctx, sdata, dev, id=id, device=dev, inputdict=inputdict, inputkeydict=inputkeydict, parentobj=parentobj, config=config, devbindobjs=devbindobjs, hopaque=opaque_args)

        
        if inputdict['tacacs_credential_set'] is not None and inputdict['device_mgmt_ip'] is None:
            dev_payload = '<device><id>'+ str(device_mgmt_ip_address) +'</id><credential-set>%s</credential-set></device>' % (inputdict['tacacs_credential_set'])

        elif inputdict['tacacs_credential_set'] is None and inputdict['device_mgmt_ip'] is not None:
            dev_payload = '<device><id>'+ str(device_mgmt_ip_address) +'</id><mgmt-ip-address>'+inputdict['device_mgmt_ip']+'</mgmt-ip-address><unique-name>'+inputdict['device_mgmt_ip']+'</unique-name></device>'
        
        elif inputdict['tacacs_credential_set'] is not None and inputdict['device_mgmt_ip'] is not None:
            dev_payload = '<device><id>'+ str(device_mgmt_ip_address) +'</id><mgmt-ip-address>'+inputdict['device_mgmt_ip']+'</mgmt-ip-address><unique-name>'+inputdict['device_mgmt_ip']+'</unique-name><credential-set>%s</credential-set></device>' % (inputdict['tacacs_credential_set'])
    
        log('device_payload: %s' % (dev_payload))
        
        for dev_iterator in dev:
            if inputdict['tacacs_credential_set'] is not None and inputdict['device_mgmt_ip'] is not None:
                yang.Sdk.patchData(dev_iterator.url+'', dev_payload, sdata, add_reference=False)

            elif inputdict['tacacs_credential_set'] is None and inputdict['device_mgmt_ip'] is not None:
                yang.Sdk.patchData(dev_iterator.url+'', dev_payload, sdata, add_reference=False)

            elif inputdict['tacacs_credential_set'] is not None and inputdict['device_mgmt_ip'] is None:
                yang.Sdk.patchData(dev_iterator.url+'', dev_payload, sdata, add_reference=False)
            

    def update(self, id, sdata):
        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'cpe_finalize')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['tacacs_credential_set'] = config.get_field_value('tacacs_credential_set')
        inputdict['device_mgmt_ip'] = config.get_field_value('device_mgmt_ip')
       
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address)

        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_update_data(smodelctx, sdata, id=id, dev=dev, parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

    def delete(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.delete_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'cpe_finalize')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['tacacs_credential_set'] = config.get_field_value('tacacs_credential_set')
        inputdict['device_mgmt_ip'] = config.get_field_value('device_mgmt_ip')
       
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address)

       

        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_delete_data(smodelctx, sdata, id=id, dev=dev, parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

       
    @staticmethod
    def getInstance():
        if(CpeFinalize._instance == None):
            CpeFinalize._instance = CpeFinalize()
        return CpeFinalize._instance

    def rollbackCreate(self, id, sdata):
        log('rollback: id = %s, sdata = %s' % (id, sdata))
        self.delete(id,sdata)

if __name__ == 'cpe_finalize':
  from servicemodel.yang import YangServiceData
  sdata = YangServiceData()
  instance = CpeFinalize().getInstance()
  instance.create(None, sdata)
  instance.delete(None, sdata)
  instance.update(None, sdata)
