#
# This computer program is the confidential information and proprietary trade
# secret of Anuta Networks, Inc. Possessions and use of this program must
# conform strictly to the license agreement between the user and
# Anuta Networks, Inc., and receipt or possession does not convey any rights
# to divulge, reproduce, or allow others to use this program without specific
# written authorization of Anuta Networks, Inc.
#
# Copyright (c) 2016-2017 Anuta Networks, Inc. All Rights Reserved.
#

#
#DO NOT EDIT THIS FILE ITS AUTOGENERATED ONE
#ALL THE CUSTOMIZATIONS REGARDING DATAPROCESSING SHOULD BE WRITTEN INTO service_customization.py FILE
#
"""
Tree Structure of Handled XPATH:

services
        |
        day1services
                    |
                    day1service
                               |
                               netflow
                                      |
                                      netflow
                                             |
                                             flow-exports
                                                         |
                                                         flow-export
                                                                    
Schema Representation:

/services/day1services/day1service/netflow/netflow/flow-exports/flow-export
"""

from servicemodel import util
from servicemodel import yang
from servicemodel import devicemgr

from tclday0config.tclday0config_lib import getLocalObject
from tclday0config.tclday0config_lib import getDeviceObject
from tclday0config.tclday0config_lib import getCurrentObjectConfig
from tclday0config.tclday0config_lib import ServiceModelContext
from tclday0config.tclday0config_lib import getParentObject
from tclday0config.tclday0config_lib import log

from servicemodel.controller.devices.device import netflow
import service_customization


class FlowExport(yang.AbstractYangServiceHandler):
    _instance = None

    def __init__(self):
        self.delete_pre_processor = service_customization.DeletePreProcessor()
        self.create_pre_processor = service_customization.CreatePreProcessor()
        self.opaque_args = {}

    def create(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.create_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'flow_export')

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['name'] = config.get_field_value('name')
        inputdict['description'] = config.get_field_value('description')
        inputdict['destination'] = config.get_field_value('destination')
        inputdict['source'] = config.get_field_value('source')
        inputdict['vrf'] = config.get_field_value('vrf')
        inputdict['udp_port_value'] = config.get_field_value('udp_port_value')
        inputdict['template_timeout'] = config.get_field_value('template_timeout')
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        # START OF FETCHING THE PARENT KEY LEAF PARAMETERS
        inputkeydict['day1services_day1service_device_ip'] = sdata.getRcPath().split('/')[-5].split('=')[1]
        # END OF FETCHING THE PARENT KEY LEAF PARAMETERS

        #Use the custom methods to process the data
        service_customization.ServiceDataCustomization.process_service_create_data(smodelctx, sdata, dev, parentobj=parentobj, inputdict=inputdict, inputkeydict=inputkeydict, config=config, hopaque=opaque_args)

        #Start of Device binding with python bindings
        netflow_object = netflow.netflow()
        netflow_flow_exports_object = netflow.flow_exports.flow_exports()
        if util.isNotEmpty(inputdict.get('name')):
            netflow_flow_exports_flow_export_object = netflow.flow_exports.flow_export.flow_export()
            netflow_flow_exports_flow_export_object.name = inputdict.get('name')
            netflow_flow_exports_flow_export_object.description = inputdict.get('description')
            netflow_flow_exports_flow_export_object.destination = inputdict.get('destination')
            netflow_flow_exports_flow_export_object.source = inputdict.get('source')
            netflow_flow_exports_flow_export_object.vrf = inputdict.get('vrf')
            netflow_flow_exports_flow_export_object.udp_port_value = inputdict.get('udp_port_value')
            netflow_flow_exports_flow_export_object.template_timeout = inputdict.get('template_timeout')


        #End of Device binding
        devbindobjs['netflow_flow_exports_flow_export_object'] = netflow_flow_exports_flow_export_object
        #Use the custom method to process/create payload
        service_customization.ServiceDataCustomization.process_service_device_bindings(smodelctx, sdata, dev, inputdict=inputdict, inputkeydict=inputkeydict, parentobj=parentobj, config=config, devbindobjs=devbindobjs, hopaque=opaque_args)
        for dev_iterator in dev:
            if dev_iterator.device.get_field_value('netflow') == None:
                yang.Sdk.createData(dev_iterator.url,'<netflow/>', sdata.getSession(), False)

            if not yang.Sdk.dataExists(dev_iterator.url+'/l3features:netflow/flow-exports'):
                yang.Sdk.createData(dev_iterator.url+'/l3features:netflow','<flow-exports/>', sdata.getSession(), False)


        netflow_flow_exports_flow_export_object_payload = netflow_flow_exports_flow_export_object.getxml(filter=True)
        log('netflow_flow_exports_flow_export_object_payload: %s' % (netflow_flow_exports_flow_export_object_payload))
        for dev_iterator in dev:
            yang.Sdk.createData(dev_iterator.url+'/l3features:netflow/flow-exports',netflow_flow_exports_flow_export_object_payload, sdata.getSession(), True)

    def update(self, id, sdata):
        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'flow_export')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['name'] = config.get_field_value('name')
        inputdict['description'] = config.get_field_value('description')
        inputdict['destination'] = config.get_field_value('destination')
        inputdict['source'] = config.get_field_value('source')
        inputdict['vrf'] = config.get_field_value('vrf')
        inputdict['udp_port_value'] = config.get_field_value('udp_port_value')
        inputdict['template_timeout'] = config.get_field_value('template_timeout')
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        prevconfig = util.parseXmlString(sdata.getPreviousPayload())


        prevconfigflowexp = prevconfig.flow_export

        #Start of Device binding with python bindings
        netflow_object = netflow.netflow()
        netflow_flow_exports_object = netflow.flow_exports.flow_exports()
        
        netflow_flow_exports_flow_export_object = netflow.flow_exports.flow_export.flow_export()
        netflow_flow_exports_flow_export_object.name = prevconfigflowexp.get_field_value('name')
        netflow_flow_exports_flow_export_object.description = inputdict.get('description')
        netflow_flow_exports_flow_export_object.destination = inputdict.get('destination')
        netflow_flow_exports_flow_export_object.source = inputdict.get('source')
        netflow_flow_exports_flow_export_object.vrf = inputdict.get('vrf')
        netflow_flow_exports_flow_export_object.udp_port_value = inputdict.get('udp_port_value')
        netflow_flow_exports_flow_export_object.template_timeout = inputdict.get('template_timeout')


        netflow_flow_exports_flow_export_object_payload = netflow_flow_exports_flow_export_object.getxml(filter=True)
        #log('netflow_flow_exports_flow_export_object_payload: %s' % (netflow_flow_exports_flow_export_object_payload))
        for dev_iterator in dev:
          yang.Sdk.createData(dev_iterator.url+'/l3features:netflow/flow-exports',netflow_flow_exports_flow_export_object_payload, sdata.getSession(), True)
        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_update_data(smodelctx, sdata, parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

    def delete(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.delete_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'flow_export')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['name'] = config.get_field_value('name')
        inputdict['description'] = config.get_field_value('description')
        inputdict['destination'] = config.get_field_value('destination')
        inputdict['source'] = config.get_field_value('source')
        inputdict['vrf'] = config.get_field_value('vrf')
        inputdict['udp_port_value'] = config.get_field_value('udp_port_value')
        inputdict['template_timeout'] = config.get_field_value('template_timeout')
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_delete_data(smodelctx, sdata,parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

    @staticmethod
    def getInstance():
        if(FlowExport._instance == None):
            FlowExport._instance = FlowExport()
        return FlowExport._instance

if __name__ == 'flow_export':
  from servicemodel.yang import YangServiceData
  sdata = YangServiceData()
  instance = FlowExport().getInstance()
  instance.create(None, sdata)
  instance.delete(None, sdata)
  instance.update(None, sdata)
