#
# This computer program is the confidential information and proprietary trade
# secret of Anuta Networks, Inc. Possessions and use of this program must
# conform strictly to the license agreement between the user and
# Anuta Networks, Inc., and receipt or possession does not convey any rights
# to divulge, reproduce, or allow others to use this program without specific
# written authorization of Anuta Networks, Inc.
#
# Copyright (c) 2015-2016 Anuta Networks, Inc. All Rights Reserved.
#

#
#DO NOT EDIT THIS FILE ITS AUTOGENERATED ONE
#ALL THE CUSTOMIZATIONS REGARDING DATAPROCESSING SHOULD BE WRITTEN INTO service_customization.py FILE
#
"""
Tree Structure of Handled XPATH:

services
        |
        day1services
                    |
                    day1service
                               |
                               features
                                       
Schema Representation:

/services/day1services/day1service/features
"""

from servicemodel import util
from servicemodel import yang
from servicemodel import devicemgr

from tclday0config.tclday0config_lib import getLocalObject
from tclday0config.tclday0config_lib import getDeviceObject
from tclday0config.tclday0config_lib import getCurrentObjectConfig
from tclday0config.tclday0config_lib import ServiceModelContext
from tclday0config.tclday0config_lib import getParentObject
from tclday0config.tclday0config_lib import log

#from servicemodel.controller import devices
from servicemodel.controller.devices.device import features
import service_customization


class Features(yang.AbstractYangServiceHandler):
    _instance = None

    def __init__(self):
        self.delete_pre_processor = service_customization.DeletePreProcessor()
        self.create_pre_processor = service_customization.CreatePreProcessor()
        self.opaque_args = {}

    def create(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.create_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'features')

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['cdp'] = config.get_field_value('cdp')
        inputdict['domain_lookup'] = config.get_field_value('domain_lookup')
        inputdict['tcp_small_servers'] = config.get_field_value('tcp_small_servers')
        inputdict['udp_small_servers'] = config.get_field_value('udp_small_servers')
        inputdict['finger'] = config.get_field_value('finger')
        inputdict['source_route'] = config.get_field_value('source_route')
        inputdict['bootp_server'] = config.get_field_value('bootp_server')
        inputdict['http_server'] = config.get_field_value('http_server')
        inputdict['http_secure_server'] = config.get_field_value('http_secure_server')
        inputdict['banner_exec'] = config.get_field_value('banner_exec')
        inputdict['banner_exec_string'] = config.get_field_value('banner_exec_string')
        inputdict['banner_login'] = config.get_field_value('banner_login')
        inputdict['banner_login_string'] = config.get_field_value('banner_login_string')
        inputdict['banner_motd'] = config.get_field_value('banner_motd')
        inputdict['banner_motd_string'] = config.get_field_value('banner_motd_string')
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        # START OF FETCHING THE PARENT KEY LEAF PARAMETERS
        inputkeydict['day1services_day1service_device_ip'] = sdata.getRcPath().split('/')[-2].split('=')[1]
        # END OF FETCHING THE PARENT KEY LEAF PARAMETERS

        #Use the custom methods to process the data
        service_customization.ServiceDataCustomization.process_service_create_data(smodelctx, sdata, dev, id=id, device=dev, parentobj=parentobj, inputdict=inputdict, inputkeydict=inputkeydict, config=config, hopaque=opaque_args)

        #Start of Device binding with python bindings
        #features_object = devices.device.features.features()
        features_object = features.features()
        features_object.cdp = inputdict.get('cdp')
        features_object.domain_lookup = inputdict.get('domain_lookup')
        features_object.tcp_small_servers = inputdict.get('tcp_small_servers')
        features_object.udp_small_servers = inputdict.get('udp_small_servers')
        features_object.finger = inputdict.get('finger')
        features_object.source_route = inputdict.get('source_route')
        features_object.bootp_server = inputdict.get('bootp_server')
        features_object.http_server = inputdict.get('http_server')
        features_object.http_secure_server = inputdict.get('http_secure_server')
        features_object.banner_exec = inputdict.get('banner_exec')
        features_object.banner_exec_string = inputdict.get('banner_exec_string')
        features_object.banner_login = inputdict.get('banner_login')
        features_object.banner_login_string = inputdict.get('banner_login_string')
        features_object.banner_motd = inputdict.get('banner_motd')
        features_object.banner_motd_string = inputdict.get('banner_motd_string')
        features_object.ip_identd = "disable"
        features_object.service_pad = "disable"


        #End of Device binding
        devbindobjs['features_object'] = features_object
        #Use the custom method to process/create payload
        service_customization.ServiceDataCustomization.process_service_device_bindings(smodelctx, sdata, dev, id=id, device=dev, inputdict=inputdict, inputkeydict=inputkeydict, parentobj=parentobj, config=config, devbindobjs=devbindobjs, hopaque=opaque_args)

        features_object_payload = features_object.getxml(filter=True)
        #log('features_object_payload: %s' % (features_object_payload))
        for dev_iterator in dev:
          yang.Sdk.createData(dev_iterator.url+'',features_object_payload, sdata.getSession(), False)

    def update(self, id, sdata):
        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'features')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['cdp'] = config.get_field_value('cdp')
        inputdict['domain_lookup'] = config.get_field_value('domain_lookup')
        inputdict['tcp_small_servers'] = config.get_field_value('tcp_small_servers')
        inputdict['udp_small_servers'] = config.get_field_value('udp_small_servers')
        inputdict['finger'] = config.get_field_value('finger')
        inputdict['source_route'] = config.get_field_value('source_route')
        inputdict['bootp_server'] = config.get_field_value('bootp_server')
        inputdict['http_server'] = config.get_field_value('http_server')
        inputdict['http_secure_server'] = config.get_field_value('http_secure_server')
        inputdict['banner_exec'] = config.get_field_value('banner_exec')
        inputdict['banner_exec_string'] = config.get_field_value('banner_exec_string')
        inputdict['banner_login'] = config.get_field_value('banner_login')
        inputdict['banner_login_string'] = config.get_field_value('banner_login_string')
        inputdict['banner_motd'] = config.get_field_value('banner_motd')
        inputdict['banner_motd_string'] = config.get_field_value('banner_motd_string')
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_update_data(smodelctx, sdata, id=id, dev=dev, parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

    def delete(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.delete_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'features')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['cdp'] = config.get_field_value('cdp')
        inputdict['domain_lookup'] = config.get_field_value('domain_lookup')
        inputdict['tcp_small_servers'] = config.get_field_value('tcp_small_servers')
        inputdict['udp_small_servers'] = config.get_field_value('udp_small_servers')
        inputdict['finger'] = config.get_field_value('finger')
        inputdict['source_route'] = config.get_field_value('source_route')
        inputdict['bootp_server'] = config.get_field_value('bootp_server')
        inputdict['http_server'] = config.get_field_value('http_server')
        inputdict['http_secure_server'] = config.get_field_value('http_secure_server')
        inputdict['banner_exec'] = config.get_field_value('banner_exec')
        inputdict['banner_exec_string'] = config.get_field_value('banner_exec_string')
        inputdict['banner_login'] = config.get_field_value('banner_login')
        inputdict['banner_login_string'] = config.get_field_value('banner_login_string')
        inputdict['banner_motd'] = config.get_field_value('banner_motd')
        inputdict['banner_motd_string'] = config.get_field_value('banner_motd_string')
        # END OF FETCHING THE LEAF PARAMETERS

        # Bugzilla Bug ID #16 - Ensure 'no ip identd' pushed to CPE when Day1 service is deleted
        features_object = features.features()
        features_object.ip_identd = "disable"
        features_object.cdp = "disable"
        features_object.domain_lookup = "disable"
        features_object.tcp_small_servers = "disable"
        features_object.udp_small_servers = "disable"
        features_object.finger = "disable"
        features_object.source_route = "disable"
        features_object.bootp_server = "disable"
        features_object.http_server = "disable"
        features_object.http_secure_server = "disable"
        features_object.service_pad = "disable"

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        features_object_payload = features_object.getxml(filter=True)
        #log('features_object_payload: %s' % (features_object_payload))
        for dev_iterator in dev:
          yang.Sdk.createData(dev_iterator.url+'',features_object_payload, sdata.getSession(), False)

        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_delete_data(smodelctx, sdata, id=id, dev=dev, parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

    @staticmethod
    def getInstance():
        if(Features._instance == None):
            Features._instance = Features()
        return Features._instance

    def rollbackCreate(self, id, sdata):
        log('rollback: id = %s, sdata = %s' % (id, sdata))
        self.delete(id,sdata)

if __name__ == 'features':
  from servicemodel.yang import YangServiceData
  sdata = YangServiceData()
  instance = Features().getInstance()
  instance.create(None, sdata)
  instance.delete(None, sdata)
  instance.update(None, sdata)
