#
# This computer program is the confidential information and proprietary trade
# secret of Anuta Networks, Inc. Possessions and use of this program must
# conform strictly to the license agreement between the user and
# Anuta Networks, Inc., and receipt or possession does not convey any rights
# to divulge, reproduce, or allow others to use this program without specific
# written authorization of Anuta Networks, Inc.
#
# Copyright (c) 2015-2016 Anuta Networks, Inc. All Rights Reserved.
#

#
#DO NOT EDIT THIS FILE ITS AUTOGENERATED ONE
#ALL THE CUSTOMIZATIONS REGARDING DATAPROCESSING SHOULD BE WRITTEN INTO service_customization.py FILE
#
"""
Tree Structure of Handled XPATH:

services
        |
        day1services
                    |
                    day1service
                               |
                               service-timestamps
                                                 
Schema Representation:

/services/day1services/day1service/service-timestamps
"""

from servicemodel import util
from servicemodel import yang
from servicemodel import devicemgr

from tclday0config.tclday0config_lib import getLocalObject
from tclday0config.tclday0config_lib import getDeviceObject
from tclday0config.tclday0config_lib import getCurrentObjectConfig
from tclday0config.tclday0config_lib import ServiceModelContext
from tclday0config.tclday0config_lib import getParentObject
from tclday0config.tclday0config_lib import log

#from servicemodel.controller import devices
from servicemodel.controller.devices.device import service_time_stamps 
import service_customization


class ServiceTimestamps(yang.AbstractYangServiceHandler):
    _instance = None

    def __init__(self):
        self.delete_pre_processor = service_customization.DeletePreProcessor()
        self.create_pre_processor = service_customization.CreatePreProcessor()
        self.opaque_args = {}

    def create(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.create_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'service_timestamps')

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['service_timestamps_debug'] = config.get_field_value('service_timestamps_debug')
        if inputdict.get('service_timestamps_debug') is None:
          inputdict['service_timestamps_debug'] = 'True'
        inputdict['service_timestamps_log'] = config.get_field_value('service_timestamps_log')
        if inputdict.get('service_timestamps_log') is None:
          inputdict['service_timestamps_log'] = 'True'
        inputdict['service_password_encryption'] = config.get_field_value('service_password_encryption')
        if inputdict.get('service_password_encryption') is None:
          inputdict['service_password_encryption'] = 'True'
        inputdict['enable_secret'] = config.get_field_value('enable_secret')
        if inputdict.get('enable_secret') is None:
          inputdict['enable_secret'] = 'False'
        inputdict['enable_secret_password'] = config.get_field_value('enable_secret_password')
        inputdict['tcp_keepalives_in'] = config.get_field_value('tcp_keepalives_in')
        if inputdict.get('tcp_keepalives_in') is None:
          inputdict['tcp_keepalives_in'] = 'False'
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        # START OF FETCHING THE PARENT KEY LEAF PARAMETERS
        inputkeydict['day1services_day1service_device_ip'] = sdata.getRcPath().split('/')[-2].split('=')[1]
        # END OF FETCHING THE PARENT KEY LEAF PARAMETERS

        #Use the custom methods to process the data
        service_customization.ServiceDataCustomization.process_service_create_data(smodelctx, sdata, dev, id=id, device=dev, parentobj=parentobj, inputdict=inputdict, inputkeydict=inputkeydict, config=config, hopaque=opaque_args)

        #Start of Device binding with python bindings
        #service_time_stamps_object = devices.device.service_time_stamps.service_time_stamps()
        service_time_stamps_object = service_time_stamps.service_time_stamps()
        service_time_stamps_object.service_timestamps_debug = inputdict.get('service_timestamps_debug')
        service_time_stamps_object.service_timestamps_log = inputdict.get('service_timestamps_log')
        service_time_stamps_object.service_password_encryption = inputdict.get('service_password_encryption')
        service_time_stamps_object.enable_secret = inputdict.get('enable_secret')
        service_time_stamps_object.enable_secret_password = inputdict.get('enable_secret_password')
        service_time_stamps_object.tcp_keepalives_in = inputdict.get('tcp_keepalives_in')


        #End of Device binding
        devbindobjs['service_time_stamps_object'] = service_time_stamps_object
        #Use the custom method to process/create payload
        service_customization.ServiceDataCustomization.process_service_device_bindings(smodelctx, sdata, dev, id=id, device=dev, inputdict=inputdict, inputkeydict=inputkeydict, parentobj=parentobj, config=config, devbindobjs=devbindobjs, hopaque=opaque_args)

        service_time_stamps_object_payload = service_time_stamps_object.getxml(filter=True)
        #log('service_time_stamps_object_payload: %s' % (service_time_stamps_object_payload))
        for dev_iterator in dev:
          yang.Sdk.createData(dev_iterator.url+'',service_time_stamps_object_payload, sdata.getSession(), True)

    def update(self, id, sdata):
        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'service_timestamps')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['service_timestamps_debug'] = config.get_field_value('service_timestamps_debug')
        if inputdict.get('service_timestamps_debug') is None:
          inputdict['service_timestamps_debug'] = 'True'
        inputdict['service_timestamps_log'] = config.get_field_value('service_timestamps_log')
        if inputdict.get('service_timestamps_log') is None:
          inputdict['service_timestamps_log'] = 'True'
        inputdict['service_password_encryption'] = config.get_field_value('service_password_encryption')
        if inputdict.get('service_password_encryption') is None:
          inputdict['service_password_encryption'] = 'True'
        inputdict['enable_secret'] = config.get_field_value('enable_secret')
        if inputdict.get('enable_secret') is None:
          inputdict['enable_secret'] = 'False'
        inputdict['enable_secret_password'] = config.get_field_value('enable_secret_password')
        inputdict['tcp_keepalives_in'] = config.get_field_value('tcp_keepalives_in')
        if inputdict.get('tcp_keepalives_in') is None:
          inputdict['tcp_keepalives_in'] = 'False'
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_update_data(smodelctx, sdata, id=id, dev=dev, parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

    def delete(self, id, sdata):
        sdata.getSession().addYangSessionPreReserveProcessor(self.delete_pre_processor)

        #Fetch Local Config Object
        config = getCurrentObjectConfig(id, sdata, 'service_timestamps')
        opaque_args = self.opaque_args

        #Fetch Service Model Context Object
        smodelctx = None

        #Fetch Parent Object
        parentobj = None

        dev = []
        inputkeydict = {}
        devbindobjs={}
        inputdict = {}
        opaque_args = self.opaque_args

        # START OF FETCHING THE LEAF PARAMETERS
        inputdict['service_timestamps_debug'] = config.get_field_value('service_timestamps_debug')
        if inputdict.get('service_timestamps_debug') is None:
          inputdict['service_timestamps_debug'] = 'True'
        inputdict['service_timestamps_log'] = config.get_field_value('service_timestamps_log')
        if inputdict.get('service_timestamps_log') is None:
          inputdict['service_timestamps_log'] = 'True'
        inputdict['service_password_encryption'] = config.get_field_value('service_password_encryption')
        if inputdict.get('service_password_encryption') is None:
          inputdict['service_password_encryption'] = 'True'
        inputdict['enable_secret'] = config.get_field_value('enable_secret')
        if inputdict.get('enable_secret') is None:
          inputdict['enable_secret'] = 'False'
        inputdict['enable_secret_password'] = config.get_field_value('enable_secret_password')
        inputdict['tcp_keepalives_in'] = config.get_field_value('tcp_keepalives_in')
        if inputdict.get('tcp_keepalives_in') is None:
          inputdict['tcp_keepalives_in'] = 'False'
        # END OF FETCHING THE LEAF PARAMETERS

        _Gen_obj = getLocalObject(sdata, 'day1service')
        device_mgmt_ip_address = _Gen_obj.day1service.device_ip

        #Fetch Device Object
        dev = getDeviceObject(device_mgmt_ip_address, sdata)

        #Use the custom method to process the data
        service_customization.ServiceDataCustomization.process_service_delete_data(smodelctx, sdata, id=id, dev=dev, parentobj=parentobj, config=config, hopaque=opaque_args, inputdict=inputdict)

    @staticmethod
    def getInstance():
        if(ServiceTimestamps._instance == None):
            ServiceTimestamps._instance = ServiceTimestamps()
        return ServiceTimestamps._instance

    def rollbackCreate(self, id, sdata):
        log('rollback: id = %s, sdata = %s' % (id, sdata))
        self.delete(id,sdata)

if __name__ == 'service_timestamps':
  from servicemodel.yang import YangServiceData
  sdata = YangServiceData()
  instance = ServiceTimestamps().getInstance()
  instance.create(None, sdata)
  instance.delete(None, sdata)
  instance.update(None, sdata)
