#
# This computer program is the confidential information and proprietary trade
# secret of Anuta Networks, Inc. Possessions and use of this program must
# conform strictly to the license agreement between the user and
# Anuta Networks, Inc., and receipt or possession does not convey any rights
# to divulge, reproduce, or allow others to use this program without specific
# written authorization of Anuta Networks, Inc.
#
# Copyright (c) 2015-2016 Anuta Networks, Inc. All Rights Reserved.
#

#
#DO NOT EDIT THIS FILE ITS AUTOGENERATED ONE
#ALL THE CUSTOMIZATIONS REGARDING DATAPROCESSING SHOULD BE WRITTEN INTO service_customization.py FILE
#

def get_plugin_info():
    return Plugin('tclday0config', '1.0.0')

from com.anuta.service.python.plugin import PythonPlugin
from com.anuta.service.python.plugin import PythonPluginType

from servicemodel import util
import Tclday0Config
from tclday0config_lib import log

class Plugin(PythonPlugin):
    """Class to register tclday0config plugin to NCX
    """
    def __init__(self, name, version):
        self.setName(name)
        self.setVersion(version)
        self.setPluginType(PythonPluginType.SERVICE_MODEL)
        self.setDescription('TCLDAY0CONFIGService Plugin')

    def init(self):
        log('registering tclday0config')
        Tclday0Config.TCLDAY0CONFIGService.getInstance().register()

    def shutdown(self):
        log('unregistering tclday0config')
        Tclday0Config.TCLDAY0CONFIGService.getInstance().unregister()
